{% set name = "skweak" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skweak-{{ version }}.tar.gz
  sha256: 640e3849f83bae6adcf45948be335fa33732aa5b97111d6df2fc1b6c5dfbca2e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - spacy >=3.0
    - hmmlearn >=0.2.5,<=0.2.7
    - pandas >=0.23
    - numpy >=1.18
    - python >=3.7

test:
  imports:
    - skweak
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NorskRegnesentral/skweak
  summary: Software toolkit for weak supervision in NLP
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
